name: 🔃 Create PRs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run the workflow without creating PRs'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 2 * * *'
jobs:
  get-branches:
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get branches
        id: get-branches
        shell: pwsh
        run: |
          $branches = git branch -r --format="%(refname:short)" | ForEach-Object { $_.Trim() -replace "^origin/", "" }
          # filter only branches that start with dev/
          $branches = $branches | Where-Object { $_ -match "^dev/" }
          $branchJson = ConvertTo-Json @($branches) -Compress
          Write-Host "branches=$branchJson"
          echo "branches=$branchJson" >> $env:GITHUB_OUTPUT
  create-pr:
    needs: get-branches
    strategy:
      max-parallel: 1
      matrix:
          branch: ${{fromJson(needs.get-branches.outputs.branches)}}
    runs-on: ubuntu-latest
    steps:
      - name: Set Branches
        run: |
          TARGET=$(echo ${{ matrix.branch }} | sed 's/dev\///')
          SOURCE=${{ matrix.branch }}

          if [ -z "$TARGET" ]; then
            echo "TARGET is empty"
            exit 1
          fi
        
          if [ -z "$SOURCE" ]; then
            echo "SOURCE is empty"
            exit 1
          fi

          if [ "$SOURCE" == "$TARGET" ]; then
            echo "SOURCE is the same as TARGET"
            exit 1
          fi

          echo "SOURCE=$SOURCE"
          echo "TARGET=$TARGET"
          echo "SOURCE=$SOURCE" >> $GITHUB_ENV
          echo "TARGET=$TARGET" >> $GITHUB_ENV
      - name: Determine Version
        id: determine-version
        run: |
          git fetch origin --all --depth=0
          git checkout $TARGET
          git merge --no-ff --no-edit $SOURCE
          git add .
          git commit -m "Merge $SOURCE into $TARGET"
      - name: Download GitVersion.yml
        shell: bash
        run: curl -sSL https://raw.githubusercontent.com/jcdcdev/jcdcdev.Umbraco.GitHub.Build/main/GitVersion.yml -o GitVersion.yml
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
          configFilePath: "GitVersion.yml"
      - name: Run the Action
        env:
          SOURCE: ${{ env.SOURCE }}
          TARGET: ${{ env.TARGET }}
          TITLE: "${{ steps.gitversion.outputs.NuGetVersionV2  }}: Merge ${{ env.SOURCE }} into ${{ env.TARGET }}"
          BODY: |
            <!-- Diff summary - START -->
            <!-- Diff summary - END -->
            <!-- Diff files - START -->
            <!-- Diff files - END -->
        if: ${{ github.event.inputs.dry-run == 'false' }} || ${{ github.event_name == 'schedule' }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.JCDC_BOT_TOKEN}}
          source_branch: ${{ env.SOURCE }}
          target_branch: ${{ env.TARGET }}
          title: ${{ env.TITLE }}
          body: ${{ env.BODY }}
          reviewer: ${{ github.repository_owner }}
          assignee: ${{ github.repository_owner }}
